# Generated by Django 3.1.1 on 2020-11-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('dateOfBirth', models.CharField(max_length=10)),
                ('bloodGroup', models.CharField(max_length=3)),
                ('emailId', models.CharField(max_length=50)),
                ('mobileNumber', models.CharField(max_length=10)),
                ('alternateMobileNumber', models.CharField(max_length=10)),
                ('addressLine1', models.CharField(max_length=50)),
                ('addressLine2', models.CharField(max_length=50)),
                ('cityOrTown', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=6)),
            ],
        ),
    ]
