# Generated by Django 3.1.1 on 2020-11-05 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(max_length=100, null=True)),
                ('lastName', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('dateOfBirth', models.DateField(max_length=10)),
                ('bloodGroup', models.CharField(max_length=3)),
                ('emailId', models.EmailField(max_length=50, unique=True)),
                ('mobileNumber', models.CharField(max_length=10)),
                ('alternateMobileNumber', models.CharField(max_length=10, null=True)),
                ('addressLine1', models.CharField(max_length=50)),
                ('addressLine2', models.CharField(max_length=50)),
                ('cityOrTown', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('pin', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insuranceProvider', models.CharField(max_length=50)),
                ('policyNumber', models.CharField(max_length=20, unique=True)),
                ('policyName', models.CharField(max_length=50)),
                ('validTill', models.DateField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appV1.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relativeName', models.CharField(max_length=100)),
                ('relationship', models.CharField(max_length=20)),
                ('primaryMobileNumber', models.CharField(max_length=10)),
                ('secondaryMobileNumber', models.CharField(max_length=10, null=True)),
                ('relativeAddress', models.CharField(max_length=100)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appV1.personalinfo')),
            ],
        ),
    ]
