# Generated by Django 3.0.8 on 2021-01-15 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appV1', '0002_auto_20210114_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalpractitionerinfo',
            name='id',
        ),
        migrations.AlterField(
            model_name='medicalpractitionerinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescriptioninfo',
            name='prescriberId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriberId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='prescriptioninfo',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userId', to=settings.AUTH_USER_MODEL),
        ),
    ]
