# Generated by Django 3.1.1 on 2020-11-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appV1', '0002_auto_20201105_0302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='bloodGroup',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('AB+', 'AB+'), ('B+', 'B+'), ('B-', 'B-')], default=None, max_length=3),
        ),
    ]
