# Generated by Django 3.1.1 on 2020-11-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appV1', '0003_auto_20201105_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='dateOfBirth',
            field=models.DateField(max_length=10),
        ),
    ]
