# Generated by Django 3.1.1 on 2020-11-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appV1', '0004_auto_20201105_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfo',
            name='bloodGroup',
            field=models.CharField(choices=[('type', 'A+'), ('type', 'AB+'), ('type', 'B+')], max_length=5),
        ),
    ]
