# Generated by Django 3.0.8 on 2020-11-06 12:25

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appV1', '0005_auto_20201105_0312'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrescriptionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addedBy', models.CharField(choices=[('Self', 'User'), ('Doctor', 'Doctor')], max_length=6)),
                ('hospitalOrClinic', models.CharField(max_length=50, null=True)),
                ('prescriberId', models.IntegerField(null=True)),
                ('doctorName', models.CharField(max_length=20, null=True)),
                ('prescriptionDate', models.DateField(default=datetime.date.today)),
                ('contactNumber', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50, null=True)),
                ('medicines', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, size=None)),
                ('prescriptionAttachment', models.ImageField(null=True, upload_to='')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appV1.PersonalInfo')),
            ],
        ),
    ]
