# Generated by Django 3.1.1 on 2020-11-05 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appV1', '0005_auto_20201105_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfo',
            name='bloodGroup',
        ),
    ]
