# Generated by Django 3.1.1 on 2020-11-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appV1', '0006_remove_personalinfo_bloodgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='bloodGroup',
            field=models.CharField(default='A+', max_length=3),
            preserve_default=False,
        ),
    ]
