# Generated by Django 3.0.8 on 2020-11-17 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appV1', '0006_prescriptioninfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orgName', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=30)),
                ('activeIndicator', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=1)),
                ('orgRegNumber', models.CharField(max_length=26, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='emergencyinfo',
            old_name='primaryMobileNumber',
            new_name='primaryContactNumber',
        ),
        migrations.RenameField(
            model_name='emergencyinfo',
            old_name='secondaryMobileNumber',
            new_name='secondaryContactNumber',
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='aadhaarCardNumber',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.CreateModel(
            name='MedicalPractitionerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('licenseNumber', models.CharField(max_length=20)),
                ('profile', models.CharField(max_length=20)),
                ('mobileNumber', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30)),
                ('activeIndicator', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=1)),
                ('orgId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appV1.OrganizationInfo')),
            ],
        ),
    ]
