# Generated by Django 3.0.8 on 2020-11-17 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appV1', '0007_auto_20201117_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptioninfo',
            name='prescriberId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appV1.MedicalPractitionerInfo'),
        ),
    ]
