# Generated by Django 3.0.8 on 2020-11-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appV1', '0008_auto_20201117_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptioninfo',
            name='notes',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='prescriptioninfo',
            name='medicines',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
