# Generated by Django 3.0.8 on 2020-11-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appV1', '0009_auto_20201117_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptioninfo',
            name='contactNumber',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
