# Generated by Django 3.0.8 on 2020-11-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appV1', '0013_auto_20201119_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodytemperature',
            name='temp',
            field=models.FloatField(),
        ),
    ]
